// Generated by tools/forge from the Orbit API definition. Do not edit by hand. (runtime copied verbatim)

// Hand-written runtime (tools/forge/runtime/sdk-go/client.go); operations.go
// next to it is generated. Standard library only.
package orbit

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// DefaultBaseURL is where the API lives unless "ORBIT_API" says otherwise.
const DefaultBaseURL = "https://dash.yunzheng.space/api/v1"

// Client calls the API with one token. The zero value is not usable; use New.
type Client struct {
	Token     string
	BaseURL   string
	HTTP      *http.Client
	UserAgent string
}

// New returns a client. An empty token falls back to "ORBIT_TOKEN".
func New(token string) *Client {
	if token == "" {
		token = os.Getenv("ORBIT_TOKEN")
	}
	base := os.Getenv("ORBIT_API")
	if base == "" {
		base = DefaultBaseURL
	}
	return &Client{Token: token, BaseURL: strings.TrimRight(base, "/"), HTTP: http.DefaultClient}
}

// Error is any non-2xx answer: {"error":{"code","message"}}.
type Error struct {
	Status  int
	Code    string
	Message string
	Body    []byte
}

func (e *Error) Error() string { return fmt.Sprintf("%d %s: %s", e.Status, e.Code, e.Message) }

// Args are the inputs of one call: path parameters by name, query
// parameters, and either a JSON body or raw bytes.
type Args struct {
	Path  map[string]any
	Query url.Values
	Body  any
	Raw   io.Reader
}

// Operation describes one endpoint (see Operations).
type Operation struct {
	Method      string
	Path        string
	Scope       string // "read" or "write"
	PathParams  []string
	QueryParams []string
	JSONBody    bool
	RawBody     bool
	Paging      string // "", "offset" or "cursor"
	SessionOnly bool
}

// Call runs an operation by its operationId and returns the raw JSON answer
// (nil for 204). Text answers (exports, raw messages) come back as a JSON string.
func (c *Client) Call(ctx context.Context, operationID string, a Args) (json.RawMessage, error) {
	op, ok := Operations[operationID]
	if !ok {
		return nil, fmt.Errorf("unknown operation %s", operationID)
	}
	path := op.Path
	for _, n := range op.PathParams {
		v, ok := a.Path[n]
		if !ok || fmt.Sprint(v) == "" {
			return nil, fmt.Errorf("%s: missing path parameter %q", operationID, n)
		}
		path = strings.Replace(path, "{"+n+"}", url.PathEscape(fmt.Sprint(v)), 1)
	}
	u := c.BaseURL + path
	if len(a.Query) > 0 {
		u += "?" + a.Query.Encode()
	}
	var body io.Reader
	ct := ""
	if op.RawBody && a.Raw != nil {
		body, ct = a.Raw, "application/octet-stream"
	} else if a.Body != nil || op.JSONBody {
		b := a.Body
		if b == nil {
			b = map[string]any{}
		}
		buf, err := json.Marshal(b)
		if err != nil {
			return nil, err
		}
		body, ct = bytes.NewReader(buf), "application/json"
	}
	req, err := http.NewRequestWithContext(ctx, op.Method, u, body)
	if err != nil {
		return nil, err
	}
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	if ct != "" {
		req.Header.Set("Content-Type", ct)
	}
	if c.UserAgent != "" {
		req.Header.Set("User-Agent", c.UserAgent)
	}
	hc := c.HTTP
	if hc == nil {
		hc = http.DefaultClient
	}
	res, err := hc.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	if res.StatusCode >= 300 {
		var e struct {
			Error struct{ Code, Message string } `json:"error"`
		}
		_ = json.Unmarshal(data, &e)
		if e.Error.Code == "" {
			e.Error.Code, e.Error.Message = "http_error", strings.TrimSpace(string(data))
		}
		return nil, &Error{Status: res.StatusCode, Code: e.Error.Code, Message: e.Error.Message, Body: data}
	}
	if res.StatusCode == 204 || len(data) == 0 {
		return nil, nil
	}
	if !strings.Contains(res.Header.Get("Content-Type"), "json") {
		s, _ := json.Marshal(string(data))
		return s, nil
	}
	return data, nil
}

// Paginate calls fn with every item of a paged list, page after page.
func (c *Client) Paginate(ctx context.Context, operationID string, a Args, fn func(item json.RawMessage) error) error {
	op, ok := Operations[operationID]
	if !ok {
		return fmt.Errorf("unknown operation %s", operationID)
	}
	q := url.Values{}
	for k, v := range a.Query {
		q[k] = v
	}
	if op.Paging == "offset" && q.Get("limit") == "" {
		q.Set("limit", "100")
	}
	a.Query = q
	for {
		raw, err := c.Call(ctx, operationID, a)
		if err != nil {
			return err
		}
		var page struct {
			Data       []json.RawMessage `json:"data"`
			Items      []json.RawMessage `json:"items"`
			Messages   []json.RawMessage `json:"messages"`
			Pagination *struct {
				NextOffset *int `json:"next_offset"`
			} `json:"pagination"`
			NextCursor any `json:"next_cursor"`
			Next       any `json:"next"`
		}
		if err := json.Unmarshal(raw, &page); err != nil {
			return err
		}
		items := page.Data
		if items == nil {
			items = page.Items
		}
		if items == nil {
			items = page.Messages
		}
		for _, it := range items {
			if err := fn(it); err != nil {
				return err
			}
		}
		if op.Paging == "" || len(items) == 0 {
			return nil
		}
		if op.Paging == "offset" {
			if page.Pagination == nil || page.Pagination.NextOffset == nil {
				return nil
			}
			q.Set("offset", fmt.Sprint(*page.Pagination.NextOffset))
			continue
		}
		next := page.NextCursor
		if next == nil {
			next = page.Next
		}
		if next == nil || fmt.Sprint(next) == q.Get("cursor") {
			return nil
		}
		q.Set("cursor", fmt.Sprint(next))
	}
}
