// Generated by tools/forge from the Orbit API definition. Do not edit by hand.
// Types for orbit.config.ts — the file `orbit plan` and `orbit apply` read.
//
//   import type { Config } from "@yunzheng/orbit-cli/config";
//   export default { zones: [...], sites: [...] } satisfies Config;

type RecordCreate = {
    name?: string;
    type: "A" | "AAAA" | "PTR" | "CNAME" | "TXT" | "MX" | "NS" | "SRV" | "CAA" | "ALIAS" | "HTTPS" | "SVCB";
    ttl?: number;
    content: string;
    weight?: number;
    health_check?: string;
  };
type RecordPatch = {
    content?: string;
    ttl?: number;
    weight?: number;
    health_check?: string;
    enabled?: boolean;
    /** Route through Orbit Shield (A/AAAA/CNAME only) */
    proxied?: boolean;
  };
type SiteCreate = {
    hostname: string;
    /** Origin IP or hostname */
    origin: string;
    origin_scheme?: "http" | "https" | "strict";
    /** Reach a hostname origin by its own name: Host and SNI are the origin hostname and the visitor's host is sent in X-Forwarded-Host. For origins that route by Host. */
    origin_host_header?: boolean;
    /** Owning DNS service; defaults to the account's first */
    service_id?: number;
  };
type SitePatch = {
    waf?: WafPatch | boolean;
    cache_ttl?: number;
    cache_mode?: "all" | "static" | "origin";
    cache_html_ttl?: number;
    force_https?: boolean;
    rate_limit?: number;
    origin_scheme?: "http" | "https" | "strict";
    origin_host_header?: boolean;
    cert_pem?: string;
    key_pem?: string;
    waiting_room?: {
      capacity?: number;
      session_min?: number;
    };
    under_attack?: boolean;
    bot_fight?: boolean;
    /** Presence sensor: off (nothing injected), observe (scored and logged only) or enforce (a navigation scoring below the threshold, or none at all from an address taking several pages a minute, meets the browser check). */
    sense?: {
      mode?: "off" | "observe" | "enforce";
      threshold?: number;
    };
    /** Measure real visitors' page loads (largest contentful paint, interaction to next paint, layout shift, first paint, time to first byte). Only anonymous histograms are kept. Changing it clears the site's edge cache. */
    rum?: boolean;
  };
type WafPatch = {
    mode?: "off" | "monitor" | "block";
    paranoia?: number;
    threshold?: number;
    exclusions?: WafExclusion[];
    body?: boolean;
    legacy?: boolean;
  };
type WafExclusion = {
    /** Rule id, as shown in the rule hits table */
    rule: number;
    /** The rule is skipped for request paths starting with this */
    path_prefix?: string;
  };

export type ConfigRecord = RecordCreate & Pick<RecordPatch, "proxied" | "enabled">;

export interface ConfigZone {
  /** The zone apex, e.g. example.com. Created when the account does not have it. */
  name: string;
  /** DNS service to create the zone in; defaults to the account's first. */
  service_id?: number;
  mode?: "zone" | "host";
  /** Record sets (name + type) listed here are made exactly so. */
  records?: ConfigRecord[];
  /** Also delete record sets this file does not mention (apex NS/SOA excepted). */
  prune?: boolean;
}

export type ConfigSite = SiteCreate & SitePatch;

export interface Config {
  zones?: ConfigZone[];
  sites?: ConfigSite[];
  /** Also delete Shield sites this file does not mention. */
  prune_sites?: boolean;
}
