# Generated by tools/forge from the Orbit API definition. Do not edit by hand.
"""Orbit API client. Standard library only.

    from orbit_api import Client
    api = Client()  # token from $ORBIT_TOKEN
    zones = api.dns.zones.list()
    for site in api.shield.sites.list.all():
        print(site["hostname"])
"""
from ._client import Client, OrbitError
from ._operations import API_VERSION, BASE_URL, OPERATIONS

__all__ = ["Client", "OrbitError", "OPERATIONS", "BASE_URL", "API_VERSION"]
__version__ = "0.1.0"
