# Generated by tools/forge from the Orbit API definition. Do not edit by hand. (runtime copied verbatim)
# Hand-written runtime (tools/forge/runtime/sdk-python/_client.py);
# _operations.py next to it is generated. Standard library only.
import json
import keyword
import os
import urllib.error
import urllib.parse
import urllib.request

from ._operations import API_VERSION, BASE_URL, OPERATIONS, TREE


class OrbitError(Exception):
    def __init__(self, status, code, message, body=None):
        super().__init__(f"{status} {code}: {message}")
        self.status, self.code, self.message, self.body = status, code, message, body


class _Namespace:
    def __init__(self, client, node):
        for name, sub in node.items():
            attr = name.replace("-", "_")
            if keyword.iskeyword(attr):
                attr += "_"
            setattr(self, attr, _bind(client, sub))


def _bind(client, node):
    if isinstance(node, str):
        op_id = node

        def call(**kwargs):
            return client.call(op_id, **kwargs)

        call.__name__ = op_id.replace(".", "_")
        call.__doc__ = f"{OPERATIONS[op_id][0]} {OPERATIONS[op_id][1]} (scope: {OPERATIONS[op_id][2]})"
        if OPERATIONS[op_id][7]:
            call.all = lambda **kwargs: client.paginate(op_id, **kwargs)
        return call
    return _Namespace(client, node)


class Client:
    """Client(token=None, base_url=None). Token defaults to $ORBIT_TOKEN."""

    def __init__(self, token=None, base_url=None, timeout=60, user_agent=None):
        self.token = token or os.environ.get("ORBIT_TOKEN")
        self.base_url = (base_url or os.environ.get("ORBIT_API") or BASE_URL).rstrip("/")
        self.timeout = timeout
        # A default User-Agent: some edges refuse urllib's own.
        self.user_agent = user_agent or "orbit-api-python/" + API_VERSION
        for product, node in TREE.items():
            setattr(self, product, _Namespace(self, node))

    def request(self, method, path, query=None, body=None, raw=None):
        url = self.base_url + path
        q = [(k, str(v).lower() if isinstance(v, bool) else str(v)) for k, v in (query or {}).items() if v is not None]
        if q:
            url += "?" + urllib.parse.urlencode(q)
        headers = {}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        if self.user_agent:
            headers["User-Agent"] = self.user_agent
        data = None
        if raw is not None:
            data = raw if isinstance(raw, (bytes, bytearray)) else str(raw).encode()
            headers["Content-Type"] = "application/octet-stream"
        elif body is not None:
            data = json.dumps(body).encode()
            headers["Content-Type"] = "application/json"
        req = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as res:
                status, ctype, text = res.status, res.headers.get("Content-Type", ""), res.read().decode("utf-8", "replace")
        except urllib.error.HTTPError as e:
            text = e.read().decode("utf-8", "replace")
            try:
                err = json.loads(text).get("error", {})
            except ValueError:
                err = {}
            raise OrbitError(e.code, err.get("code", "http_error"), err.get("message", text[:200]), text) from None
        if status == 204 or not text:
            return None
        return json.loads(text) if "json" in ctype else text

    def call(self, operation_id, **kwargs):
        op = OPERATIONS.get(operation_id)
        if op is None:
            raise TypeError(f"unknown operation {operation_id}")
        method, path, _scope, path_names, query_names, has_body, raw_body, _paging, _session = op
        path_out = path
        for n in path_names:
            if kwargs.get(n) in (None, ""):
                raise TypeError(f"{operation_id}: missing path parameter {n!r}")
            path_out = path_out.replace("{" + n + "}", urllib.parse.quote(str(kwargs.pop(n)), safe=""))
        query = {n: kwargs.pop(n) for n in query_names if n in kwargs}
        query.update(kwargs.pop("query", None) or {})
        body = kwargs.pop("body", None)
        if kwargs:
            raise TypeError(f"{operation_id}: unknown argument(s) {', '.join(sorted(kwargs))}")
        if raw_body:
            return self.request(method, path_out, query, raw=body)
        return self.request(method, path_out, query, body=body if body is not None else ({} if has_body else None))

    def paginate(self, operation_id, **kwargs):
        paging = OPERATIONS[operation_id][7]
        if paging == "offset":
            kwargs.setdefault("limit", 100)
            kwargs.setdefault("offset", 0)
        while True:
            r = self.call(operation_id, **dict(kwargs))
            items = r if isinstance(r, list) else (r or {}).get("data") or (r or {}).get("items") or (r or {}).get("messages") or []
            yield from items
            if not paging or not items:
                return
            if paging == "offset":
                nxt = ((r or {}).get("pagination") or {}).get("next_offset")
                if nxt is None:
                    return
                kwargs["offset"] = nxt
            else:
                nxt = r.get("next_cursor", r.get("next"))
                if nxt is None or nxt == kwargs.get("cursor"):
                    return
                kwargs["cursor"] = nxt
