// Generated by tools/forge from the Orbit API definition. Do not edit by hand. (runtime copied verbatim)
// Hand-written CLI runtime (tools/forge/runtime/cli/cli.mjs). The command
// table (commands.js), the vendored SDK (sdk.js) and names.js are generated.
import { readFileSync, existsSync } from "node:fs";
import { createInterface } from "node:readline";
import { COMMANDS } from "./commands.js";
import { NAMES } from "./names.js";
import { Orbit, OrbitError } from "./sdk.js";
import { loadProfiles, saveProfile, removeProfile, resolveAuth, configPath } from "./profiles.mjs";
import { planFile, printPlan, applyPlan } from "./declarative.mjs";

const BIN = NAMES.cli;
const out = (s = "") => process.stdout.write(s + "\n");
const err = (s = "") => process.stderr.write(s + "\n");
const tty = () => !!process.stdout.isTTY;
const c = (code, s) => (tty() && !process.env.NO_COLOR ? `\x1b[${code}m${s}\x1b[0m` : s);
export const color = { green: (s) => c(32, s), red: (s) => c(31, s), yellow: (s) => c(33, s), dim: (s) => c(2, s), bold: (s) => c(1, s) };

// ---- argument parsing -------------------------------------------------------
// Positionals, --flag value, --flag=value, --no-flag, and bare boolean flags.
const BOOL_FLAGS = new Set(["json", "all", "yes", "help", "h", "prune", "allow-replace", "quiet", "stdin"]);
export function parseArgs(argv) {
  const pos = [], flags = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--") { pos.push(...argv.slice(i + 1)); break; }
    if (a.startsWith("--")) {
      let [k, v] = a.slice(2).split(/=(.*)/s, 2);
      if (v === undefined) {
        if (k.startsWith("no-") && !BOOL_FLAGS.has(k)) { flags[k.slice(3)] = "false"; continue; }
        if (BOOL_FLAGS.has(k) || i + 1 >= argv.length || argv[i + 1].startsWith("--")) v = true;
        else v = argv[++i];
      }
      if (k in flags) flags[k] = [].concat(flags[k], v); else flags[k] = v;
    } else if (a === "-h") flags.help = true;
    else if (a === "-f" && i + 1 < argv.length) flags.file = argv[++i];
    else if (a === "-y") flags.yes = true;
    else pos.push(a);
  }
  return { pos, flags };
}

// ---- value coercion from the spec's types ------------------------------------
function coerce(raw, f, where) {
  const t = f.type;
  const one = (v) => {
    if (typeof v !== "string") return v;
    if (t === "integer" || t === "number") {
      const n = Number(v);
      if (!Number.isFinite(n) || (t === "integer" && !Number.isInteger(n))) throw new UsageError(`${where}: expected a number, got "${v}"`);
      return n;
    }
    if (t === "boolean") {
      if (/^(true|1|yes|on)$/i.test(v)) return true;
      if (/^(false|0|no|off)$/i.test(v)) return false;
      throw new UsageError(`${where}: expected true or false, got "${v}"`);
    }
    if (t === "object" || t === "json") { try { return JSON.parse(v); } catch { throw new UsageError(`${where}: expected JSON`); } }
    if (t === "array") {
      if (v.trim().startsWith("[")) { try { return JSON.parse(v); } catch { throw new UsageError(`${where}: expected a JSON array or a comma-separated list`); } }
      return v.split(",").map((x) => x.trim()).filter(Boolean).map((x) => (f.items === "integer" || f.items === "number" ? Number(x) : x));
    }
    if (f.enum && !f.enum.includes(v)) throw new UsageError(`${where}: must be one of ${f.enum.join(", ")}`);
    return v;
  };
  if (Array.isArray(raw)) return t === "array" ? raw.flatMap((x) => [].concat(one(x))) : one(raw[raw.length - 1]);
  if (raw === true && t !== "boolean") throw new UsageError(`${where}: needs a value`);
  return one(raw);
}

class UsageError extends Error {}

function readData(v) {
  if (v === "-" ) return JSON.parse(readFileSync(0, "utf8"));
  if (typeof v === "string" && v.startsWith("@")) return JSON.parse(readFileSync(v.slice(1), "utf8"));
  try { return JSON.parse(v); } catch { throw new UsageError("--data must be JSON, @file.json or - (stdin)"); }
}

// ---- output -----------------------------------------------------------------
const PREFERRED = ["id", "name", "hostname", "type", "content", "ttl", "status", "enabled", "proxied", "email", "state", "created_at"];
function printHuman(v) {
  if (v === null || v === undefined) { out(color.green("done")); return; }
  if (typeof v === "string") { out(v); return; }
  const list = Array.isArray(v) ? v : Array.isArray(v.data) ? v.data : Array.isArray(v.items) ? v.items : null;
  if (list) {
    if (!list.length) { out(color.dim("(none)")); return; }
    const keys = Object.keys(list[0]).filter((k) => list.every((r) => r[k] === null || typeof r[k] !== "object"));
    const cols = [...PREFERRED.filter((k) => keys.includes(k)), ...keys.filter((k) => !PREFERRED.includes(k))].slice(0, 7);
    const rows = list.map((r) => cols.map((k) => (r[k] === null || r[k] === undefined ? "" : String(r[k]))));
    const w = cols.map((k, i) => Math.min(48, Math.max(k.length, ...rows.map((r) => r[i].length))));
    const cut = (s, n) => (s.length > n ? s.slice(0, n - 1) + "…" : s);
    out(color.bold(cols.map((k, i) => k.toUpperCase().padEnd(w[i])).join("  ")));
    for (const r of rows) out(r.map((x, i) => cut(x, w[i]).padEnd(w[i])).join("  "));
    const next = v.pagination?.next_offset ?? v.next_cursor;
    if (next !== null && next !== undefined && !Array.isArray(v)) err(color.dim(`more: --${v.pagination ? "offset" : "cursor"} ${next}, or --all`));
    return;
  }
  const w = Math.max(...Object.keys(v).map((k) => k.length));
  for (const [k, x] of Object.entries(v)) out(`${color.dim(k.padEnd(w))}  ${x !== null && typeof x === "object" ? JSON.stringify(x) : x}`);
}

// ---- help -------------------------------------------------------------------
const products = () => [...new Set(COMMANDS.map((x) => x.product))];
function usage() {
  out(`${color.bold(BIN)} — ${NAMES.brand} from the command line

Usage:
  ${BIN} <product> <command> [ids…] [--field value…] [--json] [--all]
  ${BIN} plan  -f ${BIN}.config.ts        show what apply would change
  ${BIN} apply -f ${BIN}.config.ts [--yes] make it so
  ${BIN} login [--token orb_…] [--profile name]
  ${BIN} whoami | profiles | logout [--profile name]
  ${BIN} api <METHOD> <path> [--data json]

Products:
  ${products().join("  ")}

Auth: --token, then $${NAMES.envToken}, then the profile (--profile, $${NAMES.envProfile}, or the default) in ${configPath()}.
Every command: --json for machine output, --api to point at another base URL. \`${BIN} <product> --help\` lists commands.`);
}

function productHelp(p) {
  const cmds = COMMANDS.filter((x) => x.product === p);
  out(`${color.bold(`${BIN} ${p}`)} — ${cmds.length} commands\n`);
  const w = Math.max(...cmds.map((x) => cmdLine(x).length));
  for (const x of cmds) out(`  ${cmdLine(x).padEnd(w)}  ${x.scope === "write" ? color.yellow("[write]") : color.dim("[read] ")} ${x.summary}${x.sessionOnly ? color.dim(" (console only)") : ""}`);
}
const cmdLine = (x) => [x.command.join(" "), ...x.pathParams.map((p) => `<${p.name}>`)].join(" ");

function commandHelp(x) {
  out(`${color.bold(`${BIN} ${x.product} ${cmdLine(x)}`)}\n\n${x.summary}\n${x.method} ${x.path}   scope: ${x.scope}${x.sessionOnly ? "   (browser session only — tokens are refused)" : ""}\n`);
  const row = (n, f) => out(`  --${f.flag.padEnd(22)} ${f.type}${f.required ? " (required)" : ""}${f.enum ? ` one of: ${f.enum.join(", ")}` : ""}${f.description ? color.dim("  " + f.description.slice(0, 110)) : ""}`);
  if (x.pathParams.length) { out("Arguments:"); for (const p of x.pathParams) out(`  <${p.name}>${" ".repeat(Math.max(1, 23 - p.name.length))}${p.type}${p.description ? color.dim("  " + p.description) : ""}`); }
  if (x.queryParams.length) { out("Query:"); for (const f of x.queryParams) row(f.name, f); }
  if (x.bodyFields.length) { out("Body fields:"); for (const f of x.bodyFields) row(f.name, f); }
  if (x.hasBody) out(`  --data                  the whole JSON body (JSON, @file.json or -); fields above override it`);
  if (x.raw) out(`  --file                  the bytes to upload`);
  if (x.paging) out(`  --all                   fetch every page`);
}

// ---- confirmation -------------------------------------------------------------
export async function confirm(question, flags) {
  if (flags.yes) return true;
  if (!process.stdin.isTTY) throw new UsageError(`${question.replace(/\?$/, "")}: pass --yes to confirm when not running interactively.`);
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  const a = await new Promise((r) => rl.question(`${question} [y/N] `, r));
  rl.close();
  return /^y(es)?$/i.test(a.trim());
}

// ---- main ---------------------------------------------------------------------
export async function main(argv) {
  // `orbit … | head` closes the pipe early; that is not an error.
  process.stdout.on("error", (e) => { if (e.code === "EPIPE") process.exit(0); throw e; });
  const { pos, flags } = parseArgs(argv);
  try {
    if (!pos.length || (pos[0] === "help" && pos.length === 1)) { usage(); return; }
    if (pos[0] === "--version" || flags.version) { out(NAMES.version); return; }
    if (pos[0] === "help") { pos.shift(); flags.help = true; }
    const auth = () => resolveAuth(flags);
    const client = () => { const a = auth(); return new Orbit({ token: a.token, baseUrl: a.api, userAgent: `${BIN}-cli/${NAMES.version}` }); };
    const cmd = pos[0];

    if (cmd === "login") {
      const token = typeof flags.token === "string" ? flags.token : await promptToken();
      const api = typeof flags.api === "string" ? flags.api : undefined;
      const me = await new Orbit({ token, baseUrl: api }).call("me.get");
      const name = typeof flags.profile === "string" ? flags.profile : "default";
      saveProfile(name, { token, ...(api ? { api } : {}) });
      out(`${color.green("saved")} profile ${name}: ${me.email} (${me.scope || "write"})`);
      return;
    }
    if (cmd === "logout") { const n = typeof flags.profile === "string" ? flags.profile : loadProfiles().default || "default"; out(removeProfile(n) ? `removed profile ${n}` : `no profile ${n}`); return; }
    if (cmd === "profiles") { const p = loadProfiles(); for (const [n, v] of Object.entries(p.profiles || {})) out(`${n === p.default ? "*" : " "} ${n}  ${v.api || NAMES.apiBase}  ${v.token ? v.token.slice(0, 8) + "…" : ""}`); return; }
    if (cmd === "whoami") { const me = await client().call("me.get"); flags.json ? out(JSON.stringify(me, null, 2)) : printHuman({ email: me.email, auth: me.auth, scope: me.scope, principal: me.principal, api: auth().api || NAMES.apiBase, profile: auth().profile || "(env)" }); return; }
    if (cmd === "plan" || cmd === "apply") {
      const file = flags.file || flags.f || pos[1] || [`${BIN}.config.ts`, `${BIN}.config.mjs`, `${BIN}.config.json`].find((f) => existsSync(f));
      if (!file) throw new UsageError(`no config file: pass -f ${BIN}.config.ts`);
      const api = client();
      const plan = await planFile(api, file, flags);
      if (flags.json && cmd === "plan") { out(JSON.stringify(plan, null, 2)); return; }
      printPlan(plan, out, color);
      if (cmd === "plan" || !plan.changes) { if (cmd === "plan" && plan.changes) process.exitCode = 2; return; }
      if (plan.blocked.length) throw new UsageError(`${plan.blocked.length} change(s) cannot be applied as written (see above)`);
      if (!(await confirm(`Apply ${plan.changes} change(s)?`, flags))) { err("cancelled"); process.exitCode = 1; return; }
      await applyPlan(api, plan, out, color);
      return;
    }
    if (cmd === "api") {
      const [, method, path] = pos;
      if (!method || !path) throw new UsageError(`usage: ${BIN} api <METHOD> <path> [--data json]`);
      const r = await client().request(method.toUpperCase(), path.startsWith("/") ? path : "/" + path, { body: flags.data !== undefined ? readData(flags.data) : undefined });
      flags.json || typeof r !== "object" ? out(typeof r === "string" ? r : JSON.stringify(r, null, 2)) : printHuman(r);
      return;
    }

    // <product> <command…> <ids…>
    if (!products().includes(cmd)) throw new UsageError(`unknown command "${cmd}". Run ${BIN} --help.`);
    const rest = pos.slice(1);
    const cands = COMMANDS.filter((x) => x.product === cmd);
    // Longest command path matching the words given.
    let x = null;
    for (const cand of cands) {
      if (cand.command.every((w, i) => rest[i] === w) && (!x || cand.command.length > x.command.length)) x = cand;
    }
    if (!x || flags.help) {
      if (x) commandHelp(x); else if (rest.length && !flags.help) { productHelp(cmd); throw new UsageError(`unknown command "${cmd} ${rest.join(" ")}"`); } else productHelp(cmd);
      return;
    }
    const ids = rest.slice(x.command.length);
    if (ids.length < x.pathParams.length) throw new UsageError(`missing <${x.pathParams.slice(ids.length).map((p) => p.name).join("> <")}>  (usage: ${BIN} ${cmd} ${cmdLine(x)})`);
    if (ids.length > x.pathParams.length) throw new UsageError(`unexpected argument "${ids[x.pathParams.length]}"`);
    const args = {};
    x.pathParams.forEach((p, i) => { args[p.name] = coerce(ids[i], p, `<${p.name}>`); });
    for (const f of x.queryParams) { const v = flags[f.flag] ?? flags[f.flag.replace(/_/g, "-")]; if (v !== undefined) args[f.name] = coerce(v, f, `--${f.flag}`); }
    if (x.raw) {
      if (!flags.file) throw new UsageError("--file <path> is required: this command uploads bytes");
      args.body = readFileSync(flags.file);
    } else if (x.hasBody) {
      const body = flags.data !== undefined ? readData(flags.data) : {};
      for (const f of x.bodyFields) {
        if (x.queryParams.some((q) => q.name === f.name)) continue;
        const v = flags[f.flag] ?? flags[f.flag.replace(/_/g, "-")];
        if (v !== undefined) body[f.name] = coerce(v, f, `--${f.flag}`);
      }
      const missing = x.bodyFields.filter((f) => f.required && body[f.name] === undefined).map((f) => "--" + f.flag);
      if (missing.length) throw new UsageError(`missing ${missing.join(", ")}  (${BIN} ${cmd} ${x.command.join(" ")} --help)`);
      args.body = body;
    }
    if (x.method === "DELETE" && !(await confirm(`${x.summary} (${cmd} ${x.command.join(" ")} ${ids.join(" ")})?`, flags))) { err("cancelled"); process.exitCode = 1; return; }
    const api = client();
    if (flags.all && x.paging) {
      const items = [];
      for await (const it of api.paginate(x.id, args)) items.push(it);
      flags.json ? out(JSON.stringify(items, null, 2)) : printHuman(items);
      return;
    }
    const r = await api.call(x.id, args);
    if (flags.json) out(typeof r === "string" ? r : JSON.stringify(r, null, 2)); else printHuman(r);
  } catch (e) {
    if (e instanceof UsageError) { err(color.red("error: ") + e.message); process.exitCode = 64; return; }
    if (e instanceof OrbitError) {
      err(color.red(`error ${e.status} ${e.code}: `) + e.message.replace(/^\d+ [a-z_]+: /, ""));
      if (e.status === 401) err(color.dim(`sign in with: ${BIN} login --token orb_…  (or set $${NAMES.envToken})`));
      process.exitCode = 1;
      return;
    }
    if (e && /No API token/.test(e.message)) { err(color.red("error: ") + e.message); process.exitCode = 1; return; }
    throw e;
  }
}

async function promptToken() {
  if (!process.stdin.isTTY) return readFileSync(0, "utf8").trim();
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  const t = await new Promise((r) => rl.question("API token (orb_…): ", r));
  rl.close();
  return t.trim();
}
