// Generated by tools/forge from the Orbit API definition. Do not edit by hand. (runtime copied verbatim)
// Hand-written (tools/forge/runtime/cli/declarative.mjs): `plan` and `apply`
// for a config file that describes DNS zones, their records and Shield sites.
//
// Semantics (docs/design/forge-cli-mcp.md §5):
//   - A record set is (name, type). Every set the file mentions is exactly
//     what the file says: missing values are created, extra values in that
//     set are deleted, and when a set of one changes value it is updated in
//     place. Sets the file does not mention are left alone, unless the zone
//     says `prune: true` (apex NS and SOA are never pruned).
//   - A zone the account does not have yet is created (in `service_id`, or
//     the account's first DNS service).
//   - A site is matched by hostname. Missing sites are created; settings the
//     file gives are patched; sites the file does not mention are left alone
//     unless the file says `prune_sites: true`. A site's origin address cannot
//     be changed in place: that is shown as a replacement and only applied
//     with --allow-replace.
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const HOSTNAME_TYPES = new Set(["CNAME", "NS", "MX", "ALIAS", "PTR", "SRV", "HTTPS", "SVCB"]);
const RECORD_FIELDS = ["ttl", "proxied", "enabled", "weight", "health_check"];
const SITE_CREATE = ["hostname", "origin", "origin_scheme", "origin_host_header", "service_id"];
const SITE_PATCH = ["waf", "cache_ttl", "cache_mode", "cache_html_ttl", "force_https", "rate_limit", "origin_scheme", "origin_host_header", "waiting_room", "under_attack", "bot_fight", "sense"];

export async function loadConfig(file) {
  const f = resolve(file);
  if (!existsSync(f)) throw new Error(`config file not found: ${file}`);
  if (/\.json$/i.test(f)) return JSON.parse(readFileSync(f, "utf8"));
  const m = await import(pathToFileURL(f).href);
  const c = m.default ?? m.config;
  return typeof c === "function" ? await c() : c;
}

const lc = (s) => String(s ?? "").trim().toLowerCase().replace(/\.$/, "");
export function relName(name, zone) {
  const n = lc(name), z = lc(zone);
  if (!n || n === "@" || n === z) return "@";
  if (n.endsWith("." + z)) return n.slice(0, -(z.length + 1));
  return n;
}
export function normContent(type, content) {
  let c = String(content ?? "").trim();
  if (type === "TXT" && /^".*"$/s.test(c)) c = c.slice(1, -1);
  if (HOSTNAME_TYPES.has(type)) c = c.toLowerCase().replace(/\.$/, "");
  if (type === "AAAA") c = c.toLowerCase();
  return c;
}
// Every field the desired object gives is equal in the current one (deeply).
export function subsetEqual(want, have) {
  if (want === undefined) return true;
  if (want === null || typeof want !== "object") return want === have || (want === false && have === 0) || (want === true && have === 1);
  if (Array.isArray(want)) return Array.isArray(have) && want.length === have.length && want.every((w, i) => subsetEqual(w, have[i]));
  if (!have || typeof have !== "object") return false;
  return Object.entries(want).every(([k, v]) => subsetEqual(v, have[k]));
}

async function all(api, id, args = {}) {
  const out = [];
  for await (const x of api.paginate(id, args)) out.push(x);
  return out;
}

export async function planFile(api, file, flags = {}) {
  return plan(api, await loadConfig(file), flags);
}

export async function plan(api, cfg, flags = {}) {
  if (!cfg || typeof cfg !== "object") throw new Error("the config file must export an object");
  const actions = [];
  const blocked = [];
  const zonesWanted = cfg.zones || [];
  const sitesWanted = cfg.sites || [];
  const zonesHave = zonesWanted.length ? await all(api, "zones.list") : [];
  let defaultService;
  for (const zw of zonesWanted) {
    const zname = lc(zw.name);
    if (!zname) throw new Error("every zone needs a name");
    const zh = zonesHave.find((z) => lc(z.name) === zname);
    let zoneRef;
    if (!zh) {
      let sid = zw.service_id;
      if (!sid) {
        defaultService ??= (await all(api, "services.list")).find((s) => s.type === "auth_dns");
        if (!defaultService) throw new Error(`zone ${zname}: no DNS service on this account; give service_id`);
        sid = defaultService.id;
      }
      actions.push({ op: "create", kind: "zone", key: zname, call: ["zones.create", { body: { service_id: sid, name: zname, ...(zw.mode ? { mode: zw.mode } : {}) } }] });
      zoneRef = { new: zname };
    } else zoneRef = zh.id;
    const have = zh ? await all(api, "records.list", { id: zh.id }) : [];
    const want = (zw.records || []).map((r) => {
      const type = String(r.type || "").toUpperCase();
      if (!type || r.content === undefined) throw new Error(`zone ${zname}: every record needs type and content`);
      return { ...r, type, name: relName(r.name ?? "@", zname) };
    });
    const setKey = (r) => `${relName(r.name, zname)} ${String(r.type).toUpperCase()}`;
    const sets = new Map();
    for (const r of want) (sets.get(setKey(r)) || sets.set(setKey(r), { want: [], have: [] }).get(setKey(r))).want.push(r);
    for (const r of have) {
      const k = setKey(r);
      if (sets.has(k)) sets.get(k).have.push(r);
      else if (zw.prune && !(relName(r.name, zname) === "@" && ["NS", "SOA"].includes(String(r.type).toUpperCase())))
        actions.push({ op: "delete", kind: "record", key: `${zname} ${k} ${r.content}`, call: ["records.delete", { id: zoneRef, rid: r.id }] });
    }
    for (const [k, s] of sets) {
      const label = (r) => `${zname} ${k} ${r.content}`;
      const hv = [...s.have];
      const unmatched = [];
      for (const w of s.want) {
        const i = hv.findIndex((h) => normContent(w.type, h.content) === normContent(w.type, w.content));
        if (i < 0) { unmatched.push(w); continue; }
        const h = hv.splice(i, 1)[0];
        const patch = diffFields(w, h, RECORD_FIELDS);
        if (patch) actions.push({ op: "update", kind: "record", key: label(w), changes: changesOf(patch, h), call: ["records.patch", { id: zoneRef, rid: h.id, body: patch }] });
      }
      // A value that changed in a set of one: update in place, keep the id.
      if (unmatched.length === 1 && hv.length === 1) {
        const w = unmatched.pop(), h = hv.pop();
        const patch = { content: w.content, ...(diffFields(w, h, RECORD_FIELDS) || {}) };
        actions.push({ op: "update", kind: "record", key: `${zname} ${k}`, changes: changesOf(patch, h), call: ["records.patch", { id: zoneRef, rid: h.id, body: patch }] });
      }
      for (const w of unmatched) {
        const body = { name: w.name, type: w.type, content: w.content };
        for (const f of ["ttl", "weight", "health_check"]) if (w[f] !== undefined) body[f] = w[f];
        const after = {};
        for (const f of ["proxied", "enabled"]) if (w[f] !== undefined) after[f] = w[f];
        actions.push({ op: "create", kind: "record", key: label(w), call: ["records.create", { id: zoneRef, body }], ...(Object.keys(after).length ? { then: ["records.patch", after] } : {}) });
      }
      for (const h of hv) actions.push({ op: "delete", kind: "record", key: label(h), call: ["records.delete", { id: zoneRef, rid: h.id }] });
    }
  }

  if (sitesWanted.length || cfg.prune_sites) {
    const sitesHave = await all(api, "sites.list");
    for (const sw of sitesWanted) {
      const host = lc(sw.hostname);
      if (!host) throw new Error("every site needs a hostname");
      const sh = sitesHave.find((s) => lc(s.hostname) === host);
      const patchWant = {};
      for (const f of SITE_PATCH) if (sw[f] !== undefined) patchWant[f] = sw[f];
      if (!sh) {
        if (!sw.origin) throw new Error(`site ${host}: origin is required to create it`);
        const body = {};
        for (const f of SITE_CREATE) if (sw[f] !== undefined) body[f] = f === "hostname" ? host : sw[f];
        for (const f of ["origin_scheme", "origin_host_header"]) delete patchWant[f];
        actions.push({ op: "create", kind: "site", key: host, call: ["sites.create", { body }], ...(Object.keys(patchWant).length ? { then: ["sites.patch", patchWant] } : {}) });
        continue;
      }
      if (sw.origin !== undefined && sh.origin !== undefined && sh.origin !== null && lc(sw.origin) !== lc(sh.origin)) {
        const a = { op: "replace", kind: "site", key: host, changes: [`origin: ${sh.origin} -> ${sw.origin}`], calls: [["sites.delete", { id: sh.id }]], call: ["sites.create", { body: Object.fromEntries(SITE_CREATE.filter((f) => sw[f] !== undefined).map((f) => [f, f === "hostname" ? host : sw[f]])) }] };
        if (!flags["allow-replace"]) { a.blockedReason = "the origin of an existing site cannot change in place; re-run with --allow-replace to delete and re-create it"; blocked.push(a); }
        actions.push(a);
        continue;
      }
      const patch = diffFields(patchWant, sh, SITE_PATCH);
      if (patch) actions.push({ op: "update", kind: "site", key: host, changes: changesOf(patch, sh), call: ["sites.patch", { id: sh.id, body: patch }] });
    }
    if (cfg.prune_sites) {
      const keep = new Set(sitesWanted.map((s) => lc(s.hostname)));
      for (const sh of sitesHave) if (!keep.has(lc(sh.hostname))) actions.push({ op: "delete", kind: "site", key: lc(sh.hostname), call: ["sites.delete", { id: sh.id }] });
    }
  }
  return { changes: actions.length, actions, blocked: blocked.map((b) => b.key) };
}

function diffFields(want, have, fields) {
  const p = {};
  for (const f of fields) if (want[f] !== undefined && !subsetEqual(want[f], have[f])) p[f] = want[f];
  return Object.keys(p).length ? p : null;
}
const show = (v) => (v !== null && typeof v === "object" ? JSON.stringify(v) : String(v));
const changesOf = (patch, have) => Object.entries(patch).map(([k, v]) => `${k}: ${show(have[k])} -> ${show(v)}`);

export function printPlan(p, out, color) {
  if (!p.changes) { out(color.green("No changes.") + " The account matches the file."); return; }
  const sym = { create: color.green("+"), update: color.yellow("~"), delete: color.red("-"), replace: color.red("-/+") };
  for (const a of p.actions) {
    out(`${sym[a.op]} ${a.kind.padEnd(6)} ${a.key}`);
    for (const ch of a.changes || []) out(`      ${color.dim(ch)}`);
    if (a.then) out(`      ${color.dim("then set " + show(a.then[1]))}`);
    if (a.blockedReason) out(`      ${color.red("blocked: " + a.blockedReason)}`);
  }
  const n = (op) => p.actions.filter((a) => a.op === op).length;
  out(`\nPlan: ${n("create")} to create, ${n("update")} to update, ${n("delete")} to delete${n("replace") ? `, ${n("replace")} to replace` : ""}.`);
}

export async function applyPlan(api, p, out, color) {
  const zoneIds = new Map();
  const resolveId = (v) => (v && typeof v === "object" && v.new ? zoneIds.get(v.new) : v);
  // Zones first (records may need their ids), deletes of records before
  // creates in the same set so a replaced CNAME never collides.
  const order = { zone: 0, record: 1, site: 2 };
  const rank = { delete: 0, replace: 1, update: 2, create: 3 };
  const acts = [...p.actions].sort((a, b) => order[a.kind] - order[b.kind] || rank[a.op] - rank[b.op]);
  for (const a of acts) {
    for (const [id, args] of a.calls || []) await api.call(id, args);
    const [id, args] = a.call;
    const r = await api.call(id, { ...args, ...(args.id !== undefined ? { id: resolveId(args.id) } : {}) });
    if (a.kind === "zone" && a.op === "create") zoneIds.set(a.key, r.id);
    if (a.then && r && r.id !== undefined) {
      const [tid, body] = a.then;
      await api.call(tid, tid === "records.patch" ? { id: resolveId(args.id), rid: r.id, body } : { id: r.id, body });
    }
    out(`${color.green("ok")} ${a.op} ${a.kind} ${a.key}`);
  }
  out(`\nApplied ${p.changes} change(s).`);
}
