// Generated by tools/forge from the Orbit API definition. Do not edit by hand.
export const NAMES = {
  "cli": "orbit",
  "brand": "Orbit",
  "envToken": "ORBIT_TOKEN",
  "envApi": "ORBIT_API",
  "envProfile": "ORBIT_PROFILE",
  "configDir": "orbit",
  "apiBase": "https://dash.yunzheng.space/api/v1",
  "version": "0.1.0"
};
