// Generated by tools/forge from the Orbit API definition. Do not edit by hand. (runtime copied verbatim)
// Hand-written (tools/forge/runtime/cli/profiles.mjs): where the token comes
// from. Order: --token, then $ENV token, then a profile in the config file.
import { readFileSync, writeFileSync, mkdirSync, existsSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { NAMES } from "./names.js";

export function configPath() {
  const base = process.env.XDG_CONFIG_HOME || join(homedir(), ".config");
  return join(base, NAMES.configDir, "config.json");
}

export function loadProfiles() {
  const f = configPath();
  if (!existsSync(f)) return { default: "default", profiles: {} };
  try { return JSON.parse(readFileSync(f, "utf8")); } catch { return { default: "default", profiles: {} }; }
}

function write(cfg) {
  const f = configPath();
  mkdirSync(dirname(f), { recursive: true, mode: 0o700 });
  writeFileSync(f, JSON.stringify(cfg, null, 2) + "\n", { mode: 0o600 });
  chmodSync(f, 0o600);
}

export function saveProfile(name, data) {
  const cfg = loadProfiles();
  cfg.profiles ||= {};
  cfg.profiles[name] = data;
  if (!cfg.default || !cfg.profiles[cfg.default]) cfg.default = name;
  write(cfg);
}

export function removeProfile(name) {
  const cfg = loadProfiles();
  if (!cfg.profiles?.[name]) return false;
  delete cfg.profiles[name];
  if (cfg.default === name) cfg.default = Object.keys(cfg.profiles)[0] || "default";
  write(cfg);
  return true;
}

export function resolveAuth(flags = {}) {
  const api = typeof flags.api === "string" ? flags.api : process.env[NAMES.envApi];
  if (typeof flags.token === "string") return { token: flags.token, api };
  if (process.env[NAMES.envToken]) return { token: process.env[NAMES.envToken], api };
  const cfg = loadProfiles();
  const name = typeof flags.profile === "string" ? flags.profile : process.env[NAMES.envProfile] || cfg.default;
  const p = cfg.profiles?.[name];
  if (!p || !p.token) throw new Error(`No API token. Run \`${NAMES.cli} login\`, pass --token, or set $${NAMES.envToken}.`);
  return { token: p.token, api: api || p.api, profile: name };
}
